rm (list = ls(all=TRUE))
graphics.off()
installl.package("qrmdata")
install.packages("xts")
install.packages("mvtnorm", dependencies = TRUE)
install.packages("QRM", dependencies = TRUE)
install.packages("qrmtools")
install.packages("PerformanceAnalytics", dependencies = TRUE)
library(PerformanceAnalytics)
library(qrmtools)
library(qrmdata)
library(xts)
library(mvtnorm)
library(QRM)
mu<-0
sigma<-1
xvals <- seq(from = -4*sigma, to = 4*sigma, length.out = 1000000)
ndens <- dnorm(xvals, mean = mu, sd = sigma)
plot(xvals, ndens, type = "l")
VaR99 <- qnorm(0.99, mean = mu, sd = sigma)
ES99 <- ESnorm(0.99, mu = mu, sd = sigma)
abline(v = VaR99, col = "red")
abline(v = ES99, col = "green")